#==============================================================================
# AI Model Configuration
#==============================================================================
model_config:
  service_provider: openai            # AI service provider (e.g., openai, azure)
  model_name: gpt-4o-mini            # Model to use for text generation
  api_keys: ~   # Your API key (optional)
  temperature: 0                # Temperature for text generation
  max_tokens: 10000                  # Maximum number of tokens to generate
  rate_limit: 5                      # Rate limit for API calls (requests per second)

embedding_config:
  service_provider: openai_embedding  # Embedding service provider
  embedding_model_name: text-embedding-3-small  # Model for text embeddings
  api_keys: ~   # Your API key (optional)
  rate_limit: 5                      # Rate limit for embedding requests
config:
  main_folder: ~
  n: 8
  top_k: 10
  wait_till_success: False
  task: web search
  language: en
